#!/bin/sh
GIT_WORK_TREE=/var/www/www.firethoughts.mu git checkout -f
chown -R www-data:www-data /var/www/www.firethoughts.mu && chgrp -R www-data /var/www/www.firethoughts.mu && chmod -R g+w /var/www/www.firethoughts.mu && find /var/www/www.firethoughts.mu -type d -exec chmod g+s {} \;