fixtures = (
    # ordering matters here because of dependencies
    'sites.site',
    'post_office.emailtemplate',
    'socialaccount.socialapp',
    'accounts.user',
    'accounts.userprofile',
    'core.industry',
    'core.language',
    'geo.country',
    'geo.location',
    'geo.nationality',
    # 'organisations.organisation',
    # 'industries.industry',
    # 'qualifications.language',
    # #'qualifications.license',
    # #'qualifications.membership',
    # #'qualifications.skill',
    # 'companies.company',
    # #'jobs.job',
)
